LOCAL_PATH := $(LOCAL_PATH)

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    $(LOCAL_PATH)/proprietary/bin/btnvtool:system/bin/btnvtool \
    $(LOCAL_PATH)/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(LOCAL_PATH)/proprietary/bin/irsc_util:system/bin/irsc_util \
    $(LOCAL_PATH)/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    $(LOCAL_PATH)/proprietary/bin/location-mq:system/bin/location-mq \
    $(LOCAL_PATH)/proprietary/bin/lowi-server:system/bin/lowi-server \
    $(LOCAL_PATH)/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    $(LOCAL_PATH)/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(LOCAL_PATH)/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    $(LOCAL_PATH)/proprietary/bin/netmgrd:system/bin/netmgrd \
    $(LOCAL_PATH)/proprietary/bin/pm-service:system/bin/pm-service \
    $(LOCAL_PATH)/proprietary/bin/qmuxd:system/bin/qmuxd \
    $(LOCAL_PATH)/proprietary/bin/qemud:system/bin/qemud \
    $(LOCAL_PATH)/proprietary/bin/qseecomd:system/bin/qseecomd \
    $(LOCAL_PATH)/proprietary/bin/radish:system/bin/radish \
    $(LOCAL_PATH)/proprietary/bin/rfs_access:system/bin/rfs_access \
    $(LOCAL_PATH)/proprietary/bin/rmnetcli:system/bin/rmnetcli \
    $(LOCAL_PATH)/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    $(LOCAL_PATH)/proprietary/bin/SensorCali:system/bin/SensorCali \
    $(LOCAL_PATH)/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
    $(LOCAL_PATH)/proprietary/bin/time_daemon:system/bin/time_daemon \
    $(LOCAL_PATH)/proprietary/bin/wdsdaemon:system/bin/wdsdaemon \
    $(LOCAL_PATH)/proprietary/bin/wfdservice:system/bin/wfdservice \
    $(LOCAL_PATH)/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    $(LOCAL_PATH)/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    $(LOCAL_PATH)/proprietary/etc/hsic.control.bt.sh:system/etc/hsic.control.bt.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.audio.sh:system/etc/init.qcom.audio.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.efs.sync.sh:system/etc/init.qcom.efs.sync.sh \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_General_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Global_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Handset_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Hdmi_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Headset_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Speaker_cal.acdb:system/etc/acdbdata/MTP/msm8939-tapan-snd-card/MTP_WCD9306_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_General_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Global_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Handset_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Hdmi_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Headset_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Speaker_cal.acdb:system/etc/acdbdata/QRD/msm8939-snd-card-skul/QRD_SKUL_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    $(LOCAL_PATH)/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    $(LOCAL_PATH)/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    $(LOCAL_PATH)/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    $(LOCAL_PATH)/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cardapp.b00:system/etc/firmware/cardapp.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/cardapp.b01:system/etc/firmware/cardapp.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/cardapp.b02:system/etc/firmware/cardapp.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/cardapp.b03:system/etc/firmware/cardapp.b03 \
    $(LOCAL_PATH)/proprietary/etc/firmware/cardapp.mdt:system/etc/firmware/cardapp.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/goodixfp.b00:system/etc/firmware/goodixfp.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/goodixfp.b01:system/etc/firmware/goodixfp.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/goodixfp.b02:system/etc/firmware/goodixfp.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/goodixfp.b03:system/etc/firmware/goodixfp.b03 \
    $(LOCAL_PATH)/proprietary/etc/firmware/goodixfp.mdt:system/etc/firmware/goodixfp.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    $(LOCAL_PATH)/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/hbtp/hbtp_rohm_ql1500_np.cfg:system/etc/firmware/hbtp/hbtp_rohm_ql1500_np.cfg \
    $(LOCAL_PATH)/proprietary/etc/firmware/hbtp/hbtp_rohm_ql1500_np.dat:system/etc/firmware/hbtp/hbtp_rohm_ql1500_np.dat \
    $(LOCAL_PATH)/proprietary/etc/firmware/modem_config/cmcc_mcfg_sw.mbn:system/etc/firmware/modem_config/cmcc_mcfg_sw.mbn \
    $(LOCAL_PATH)/proprietary/etc/firmware/modem_config/ct_mcfg_sw.mbn:system/etc/firmware/modem_config/ct_mcfg_sw.mbn \
    $(LOCAL_PATH)/proprietary/etc/firmware/modem_config/cu_mcfg_sw.mbn:system/etc/firmware/modem_config/cu_mcfg_sw.mbn \
    $(LOCAL_PATH)/proprietary/etc/firmware/modem_config/row_mcfg_sw.mbn:system/etc/firmware/modem_config/row_mcfg_sw.mbn \
    $(LOCAL_PATH)/proprietary/etc/firmware/modem_config/ytl_mcfg_sw.mbn:system/etc/firmware/modem_config/ytl_mcfg_sw.mbn \
    $(LOCAL_PATH)/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/ConnectivityExt.xml:system/etc/permissions/ConnectivityExt.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    $(LOCAL_PATH)/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    $(LOCAL_PATH)/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    $(LOCAL_PATH)/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    $(LOCAL_PATH)/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    $(LOCAL_PATH)/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    $(LOCAL_PATH)/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar \
    $(LOCAL_PATH)/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    $(LOCAL_PATH)/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(LOCAL_PATH)/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(LOCAL_PATH)/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
    $(LOCAL_PATH)/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    $(LOCAL_PATH)/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(LOCAL_PATH)/proprietary/lib/libtinyxml2.so:system/lib/libtinyxml2.so \
    $(LOCAL_PATH)/proprietary/lib64/libmm-omxcore.so:system/lib64/libmm-omxcore.so \
    $(LOCAL_PATH)/proprietary/lib64/libtinyxml2.so:system/lib64/libtinyxml2.so \
    $(LOCAL_PATH)/proprietary/lib64/libwcnss_qmi.so:system/lib64/libwcnss_qmi.so \
    $(LOCAL_PATH)/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    $(LOCAL_PATH)/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.vendor.msm8916.so \
    $(LOCAL_PATH)/proprietary/lib64/hw/sensors.msm8916.so:system/lib64/hw/sensors.msm8916.so \
    $(LOCAL_PATH)/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
    $(LOCAL_PATH)/proprietary/vendor/bin/hbtp_daemon:system/vendor/bin/hbtp_daemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    $(LOCAL_PATH)/proprietary/vendor/bin/slim_daemon:system/vendor/bin/slim_daemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    $(LOCAL_PATH)/proprietary/vendor/firmware/keymaste.b00:system/vendor/firmware/keymaste.b00 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/keymaste.b01:system/vendor/firmware/keymaste.b01 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/keymaste.b02:system/vendor/firmware/keymaste.b02 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/keymaste.b03:system/vendor/firmware/keymaste.b03 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/keymaste.mdt:system/vendor/firmware/keymaste.mdt \
    $(LOCAL_PATH)/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libarcsoft_beauty_shot.so:system/vendor/lib/libarcsoft_beauty_shot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libasn1cper.so:system/vendor/lib/libasn1cper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libasn1crt.so:system/vendor/lib/libasn1crt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libasn1crtx.so:system/vendor/lib/libasn1crtx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcamerahandler_jni.so:system/vendor/lib/libcamerahandler_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcsvt_jni.so:system/vendor/lib/libcsvt_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdmjni.so:system/vendor/lib/libdmjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libextendedremotedisplay.so:system/vendor/lib/libextendedremotedisplay.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFaceProc.so:system/vendor/lib/libFaceProc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libhbtparm.so:system/vendor/lib/libhbtparm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libhbtpclient.so:system/vendor/lib/libhbtpclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libhbtpfrmwk.so:system/vendor/lib/libhbtpfrmwk.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libhbtptouchmgrjni.so:system/vendor/lib/libhbtptouchmgrjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_gc2355_8916.so:system/vendor/lib/libmmcamera_gc2355_8916.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imx219_q8n13a.so:system/vendor/lib/libmmcamera_imx219_q8n13a.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov13850_eeprom.so:system/vendor/lib/libmmcamera_ov13850_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov13853_eeprom.so:system/vendor/lib/libmmcamera_ov13853_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov13853_q13853a.so:system/vendor/lib/libmmcamera_ov13853_q13853a.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov2680_5987fhq.so:system/vendor/lib/libmmcamera_ov2680_5987fhq.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov2680_skuhf.so:system/vendor/lib/libmmcamera_ov2680_skuhf.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov2680.so:system/vendor/lib/libmmcamera_ov2680.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov5670_86001.so:system/vendor/lib/libmmcamera_ov5670_86001.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov5670_a11.so:system/vendor/lib/libmmcamera_ov5670_a11.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov5670_eeprom.so:system/vendor/lib/libmmcamera_ov5670_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov8865_a11_eeprom.so:system/vendor/lib/libmmcamera_ov8865_a11_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov8865_a11.so:system/vendor/lib/libmmcamera_ov8865_a11.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k3h7_8916.so:system/vendor/lib/libmmcamera_s5k3h7_8916.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k3h7_eeprom.so:system/vendor/lib/libmmcamera_s5k3h7_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k3l2.so:system/vendor/lib/libmmcamera_s5k3l2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k3l8_eeprom.so:system/vendor/lib/libmmcamera_s5k3l8_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k3l8.so:system/vendor/lib/libmmcamera_s5k3l8.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k5e8_eeprom.so:system/vendor/lib/libmmcamera_s5k5e8_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_s5k5e8.so:system/vendor/lib/libmmcamera_s5k5e8.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sp2508.so:system/vendor/lib/libmmcamera_sp2508.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so:system/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmasc.so:system/vendor/lib/libmasc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmdsprpc.so:system/vendor/lib/libmdsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libomx_amrdec_sharedlibrary.so:system/vendor/lib/libomx_amrdec_sharedlibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libomx_amrenc_sharedlibrary.so:system/vendor/lib/libomx_amrenc_sharedlibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libomx_sharedlibrary.so:system/vendor/lib/libomx_sharedlibrary.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqcom_omx.so:system/vendor/lib/libqcom_omx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libts_detected_face_hal.so:system/vendor/lib/libts_detected_face_hal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libts_face_beautify_hal.so:system/vendor/lib/libts_face_beautify_hal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvt_engine.so:system/vendor/lib/libvt_engine.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwbc_jni.so:system/vendor/lib/libwbc_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdservice.so:system/vendor/lib/libwfdservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdbmapper.so:system/vendor/lib64/libacdbmapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libalarmservice_jni.so:system/vendor/lib64/libalarmservice_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libaudioalsa.so:system/vendor/lib64/libaudioalsa.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcalmodule_akm.so:system/vendor/lib64/libcalmodule_akm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcalmodule_common.so:system/vendor/lib64/libcalmodule_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libextendedremotedisplay.so:system/vendor/lib64/libextendedremotedisplay.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libFileMux.so:system/vendor/lib64/libFileMux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhandbioalgojni.so:system/vendor/lib64/libhandbioalgojni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhandbioalgo.so:system/vendor/lib64/libhandbioalgo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhbtparm.so:system/vendor/lib64/libhbtparm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhbtpclient.so:system/vendor/lib64/libhbtpclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhbtpfrmwk.so:system/vendor/lib64/libhbtpfrmwk.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhbtptouchmgrjni.so:system/vendor/lib64/libhbtptouchmgrjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libhwdaphal.so:system/vendor/lib64/libhwdaphal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/lib-imsdpl.so:system/vendor/lib64/lib-imsdpl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblistenjni.so:system/vendor/lib64/liblistenjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblistensoundmodel2.so:system/vendor/lib64/liblistensoundmodel2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libloc_ext.so:system/vendor/lib64/libloc_ext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libloc_xtra.so:system/vendor/lib64/libloc_xtra.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmasc.so:system/vendor/lib64/libmasc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmdmdetect.so:system/vendor/lib64/libmdmdetect.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmdsprpc.so:system/vendor/lib64/libmdsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera2_frame_algorithm.so:system/vendor/lib64/libmmcamera2_frame_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera2_q3a_core.so:system/vendor/lib64/libmmcamera2_q3a_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:system/vendor/lib64/libmmcamera2_stats_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera_gc2355_8916.so:system/vendor/lib64/libmmcamera_gc2355_8916.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera_imx219_q8n13a.so:system/vendor/lib64/libmmcamera_imx219_q8n13a.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera_ov8858.so:system/vendor/lib64/libmmcamera_ov8858.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libmmcamera_sp2508.so:system/vendor/lib64/libmmcamera_sp2508.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libNimsWrap.so:system/vendor/lib64/libNimsWrap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOmxAacDec.so:system/vendor/lib64/libOmxAacDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOmxMux.so:system/vendor/lib64/libOmxMux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libperipheral_client.so:system/vendor/lib64/libperipheral_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqcci_legacy.so:system/vendor/lib64/libqcci_legacy.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_client_qmux.so:system/vendor/lib64/libqmi_client_qmux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmiservices.so:system/vendor/lib64/libqmiservices.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqmi.so:system/vendor/lib64/libqmi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsd_sdk_display.so:system/vendor/lib64/libsd_sdk_display.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libSecureUILib.so:system/vendor/lib64/libSecureUILib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsecureui.so:system/vendor/lib64/libsecureui.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsecureuisvc_jni.so:system/vendor/lib64/libsecureuisvc_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsecureui_svcsock.so:system/vendor/lib64/libsecureui_svcsock.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libSHIMDivxDrm.so:system/vendor/lib64/libSHIMDivxDrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libStDrvInt.so:system/vendor/lib64/libStDrvInt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsubsystem_control.so:system/vendor/lib64/libsubsystem_control.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libSubSystemShutdown.so:system/vendor/lib64/libSubSystemShutdown.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libtzdrmgenprov.so:system/vendor/lib64/libtzdrmgenprov.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libuiblur.so:system/vendor/lib64/libuiblur.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libvcel.so:system/vendor/lib64/libvcel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libvendorconn.so:system/vendor/lib64/libvendorconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwbc_jni.so:system/vendor/lib64/libwbc_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdcommonutils.so:system/vendor/lib64/libwfdcommonutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdhdcpcp.so:system/vendor/lib64/libwfdhdcpcp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdmmsink.so:system/vendor/lib64/libwfdmmsink.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdmmsrc.so:system/vendor/lib64/libwfdmmsrc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdmmutils.so:system/vendor/lib64/libwfdmmutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdnative.so:system/vendor/lib64/libwfdnative.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdrtsp.so:system/vendor/lib64/libwfdrtsp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdservice.so:system/vendor/lib64/libwfdservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfdsm.so:system/vendor/lib64/libwfdsm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfduibcinterface.so:system/vendor/lib64/libwfduibcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfduibcsinkinterface.so:system/vendor/lib64/libwfduibcsinkinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfduibcsink.so:system/vendor/lib64/libwfduibcsink.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfduibcsrcinterface.so:system/vendor/lib64/libwfduibcsrcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwfduibcsrc.so:system/vendor/lib64/libwfduibcsrc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libwqe.so:system/vendor/lib64/libwqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxt_native.so:system/vendor/lib64/libxt_native.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libxtwifi_zpp_adaptor.so:system/vendor/lib64/libxtwifi_zpp_adaptor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so \
    $(LOCAL_PATH)/proprietary/vendor/etc/msm_irqbalance.conf:system/vendor/etc/msm_irqbalance.conf \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so:system/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camera.so:system/vendor/lib/libactuator_bu64297_q13v06k_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_bu64297_q13v06k.so:system/vendor/lib/libactuator_bu64297_q13v06k.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_13p1ba_h2x_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_h2x_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_13p1ba_h2x_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_h2x_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_13p1ba_h2x.so:system/vendor/lib/libactuator_dw9714_13p1ba_h2x.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:system/vendor/lib/libactuator_dw9714_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_camera.so:system/vendor/lib/libactuator_dw9714_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_meituosi_h2x_camcorder.so:system/vendor/lib/libactuator_dw9714_meituosi_h2x_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_meituosi_h2x_camera.so:system/vendor/lib/libactuator_dw9714_meituosi_h2x_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_meituosi_h2x.so:system/vendor/lib/libactuator_dw9714_meituosi_h2x.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_sikao_h2x_camcorder.so:system/vendor/lib/libactuator_dw9714_sikao_h2x_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_sikao_h2x_camera.so:system/vendor/lib/libactuator_dw9714_sikao_h2x_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714_sikao_h2x.so:system/vendor/lib/libactuator_dw9714_sikao_h2x.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9718s_camcorder.so:system/vendor/lib/libactuator_dw9718s_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9718s_camera.so:system/vendor/lib/libactuator_dw9718s_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9718s.so:system/vendor/lib/libactuator_dw9718s.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9718s_sunny_a11_camcorder.so:system/vendor/lib/libactuator_dw9718s_sunny_a11_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9718s_sunny_a11_camera.so:system/vendor/lib/libactuator_dw9718s_sunny_a11_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9718s_sunny_a11.so:system/vendor/lib/libactuator_dw9718s_sunny_a11.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9761b_camcorder.so:system/vendor/lib/libactuator_dw9761b_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9761b_camera.so:system/vendor/lib/libactuator_dw9761b_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9761b_ov13853_camcorder.so:system/vendor/lib/libactuator_dw9761b_ov13853_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9761b_ov13853_camera.so:system/vendor/lib/libactuator_dw9761b_ov13853_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9761b_ov13853.so:system/vendor/lib/libactuator_dw9761b_ov13853.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_dw9761b.so:system/vendor/lib/libactuator_dw9761b.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_a11_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_a11_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_a11_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_a11_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_a11.so:system/vendor/lib/libactuator_rohm_bu64243gwz_a11.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_h2x_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_h2x_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_h2x_camera.so:system/vendor/lib/libactuator_rohm_bu64243gwz_h2x_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_h2x.so:system/vendor/lib/libactuator_rohm_bu64243gwz_h2x.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64244_camcorder.so:system/vendor/lib/libactuator_rohm_bu64244_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64244_camera.so:system/vendor/lib/libactuator_rohm_bu64244_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_rohm_bu64244.so:system/vendor/lib/libactuator_rohm_bu64244.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libactuator_dw9718s_camcorder.so:system/vendor/lib64/libactuator_dw9718s_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libactuator_dw9718s_camera.so:system/vendor/lib64/libactuator_dw9718s_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libactuator_dw9718s.so:system/vendor/lib64/libactuator_dw9718s.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libactuator_dw9718s_sunny_a11_camcorder.so:system/vendor/lib64/libactuator_dw9718s_sunny_a11_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libactuator_dw9718s_sunny_a11_camera.so:system/vendor/lib64/libactuator_dw9718s_sunny_a11_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_8916_common.so:system/vendor/lib/libchromatix_gc2355_8916_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_8916_default_video.so:system/vendor/lib/libchromatix_gc2355_8916_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_8916_preview.so:system/vendor/lib/libchromatix_gc2355_8916_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx219_q8n13a_common.so:system/vendor/lib/libchromatix_imx219_q8n13a_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx219_q8n13a_default_video.so:system/vendor/lib/libchromatix_imx219_q8n13a_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so:system/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx219_q8n13a_preview.so:system/vendor/lib/libchromatix_imx219_q8n13a_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so:system/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_hfr_120fps.so:system/vendor/lib/libchromatix_ov13850_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_hfr_60fps.so:system/vendor/lib/libchromatix_ov13850_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_hfr_90fps.so:system/vendor/lib/libchromatix_ov13850_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_common.so:system/vendor/lib/libchromatix_ov13853_q13853a_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_default_video.so:system/vendor/lib/libchromatix_ov13853_q13853a_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_hfr_120fps.so:system/vendor/lib/libchromatix_ov13853_q13853a_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_hfr_60fps.so:system/vendor/lib/libchromatix_ov13853_q13853a_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_hfr_90fps.so:system/vendor/lib/libchromatix_ov13853_q13853a_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_preview.so:system/vendor/lib/libchromatix_ov13853_q13853a_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov13853_q13853a_snapshot.so:system/vendor/lib/libchromatix_ov13853_q13853a_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_common.so:system/vendor/lib/libchromatix_ov2680_5987fhq_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:system/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_preview.so:system/vendor/lib/libchromatix_ov2680_5987fhq_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:system/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_common.so:system/vendor/lib/libchromatix_ov2680_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_default_video.so:system/vendor/lib/libchromatix_ov2680_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_preview.so:system/vendor/lib/libchromatix_ov2680_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov2680_snapshot.so:system/vendor/lib/libchromatix_ov2680_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_common.so:system/vendor/lib/libchromatix_ov5670_86001_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_default_video.so:system/vendor/lib/libchromatix_ov5670_86001_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_86001_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_86001_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_86001_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_liveshot.so:system/vendor/lib/libchromatix_ov5670_86001_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_preview.so:system/vendor/lib/libchromatix_ov5670_86001_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_snapshot.so:system/vendor/lib/libchromatix_ov5670_86001_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_video_hd.so:system/vendor/lib/libchromatix_ov5670_86001_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_86001_zsl.so:system/vendor/lib/libchromatix_ov5670_86001_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_common.so:system/vendor/lib/libchromatix_ov5670_a11_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_default_video.so:system/vendor/lib/libchromatix_ov5670_a11_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_a11_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_a11_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_a11_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_liveshot.so:system/vendor/lib/libchromatix_ov5670_a11_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_preview.so:system/vendor/lib/libchromatix_ov5670_a11_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_snapshot.so:system/vendor/lib/libchromatix_ov5670_a11_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_common.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_default_video.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_liveshot.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_preview.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_snapshot.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_video_hd.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_zsl.so:system/vendor/lib/libchromatix_ov5670_a11_sunny_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_video_hd.so:system/vendor/lib/libchromatix_ov5670_a11_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_a11_zsl.so:system/vendor/lib/libchromatix_ov5670_a11_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_qtech_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_sunny_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_common.so:system/vendor/lib/libchromatix_ov8858_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:system/vendor/lib/libchromatix_ov8858_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib/libchromatix_ov8858_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib/libchromatix_ov8858_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib/libchromatix_ov8858_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:system/vendor/lib/libchromatix_ov8858_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_preview.so:system/vendor/lib/libchromatix_ov8858_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:system/vendor/lib/libchromatix_ov8858_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_common.so:system/vendor/lib/libchromatix_ov8865_a11_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_default_video.so:system/vendor/lib/libchromatix_ov8865_a11_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_a11_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_a11_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_a11_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_liveshot.so:system/vendor/lib/libchromatix_ov8865_a11_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_preview.so:system/vendor/lib/libchromatix_ov8865_a11_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_snapshot.so:system/vendor/lib/libchromatix_ov8865_a11_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_common.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_default_video.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_liveshot.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_preview.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_snapshot.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_video_hd.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_zsl.so:system/vendor/lib/libchromatix_ov8865_a11_sunny_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_video_hd.so:system/vendor/lib/libchromatix_ov8865_a11_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_a11_zsl.so:system/vendor/lib/libchromatix_ov8865_a11_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_common.so:system/vendor/lib/libchromatix_ov8865_qtech_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_default_video.so:system/vendor/lib/libchromatix_ov8865_qtech_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_qtech_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_qtech_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_qtech_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_liveshot.so:system/vendor/lib/libchromatix_ov8865_qtech_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_preview.so:system/vendor/lib/libchromatix_ov8865_qtech_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_snapshot.so:system/vendor/lib/libchromatix_ov8865_qtech_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_video_hd.so:system/vendor/lib/libchromatix_ov8865_qtech_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_qtech_zsl.so:system/vendor/lib/libchromatix_ov8865_qtech_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_common.so:system/vendor/lib/libchromatix_ov8865_sunny_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_default_video.so:system/vendor/lib/libchromatix_ov8865_sunny_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_sunny_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_sunny_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_sunny_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_liveshot.so:system/vendor/lib/libchromatix_ov8865_sunny_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_preview.so:system/vendor/lib/libchromatix_ov8865_sunny_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_snapshot.so:system/vendor/lib/libchromatix_ov8865_sunny_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_video_hd.so:system/vendor/lib/libchromatix_ov8865_sunny_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_ov8865_sunny_zsl.so:system/vendor/lib/libchromatix_ov8865_sunny_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3h7_8916_common.so:system/vendor/lib/libchromatix_s5k3h7_8916_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3h7_8916_default_video.so:system/vendor/lib/libchromatix_s5k3h7_8916_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3h7_8916_preview.so:system/vendor/lib/libchromatix_s5k3h7_8916_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3h7_8916_snapshot.so:system/vendor/lib/libchromatix_s5k3h7_8916_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_common.so:system/vendor/lib/libchromatix_s5k3l2_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_default_video.so:system/vendor/lib/libchromatix_s5k3l2_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l2_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l2_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l2_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_liveshot.so:system/vendor/lib/libchromatix_s5k3l2_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_preview.so:system/vendor/lib/libchromatix_s5k3l2_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_snapshot.so:system/vendor/lib/libchromatix_s5k3l2_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_video_hd.so:system/vendor/lib/libchromatix_s5k3l2_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l2_zsl.so:system/vendor/lib/libchromatix_s5k3l2_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_common.so:system/vendor/lib/libchromatix_s5k3l8_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_default_video.so:system/vendor/lib/libchromatix_s5k3l8_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l8_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l8_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l8_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_preview.so:system/vendor/lib/libchromatix_s5k3l8_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_common.so:system/vendor/lib/libchromatix_s5k3l8_qtech_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_default_video.so:system/vendor/lib/libchromatix_s5k3l8_qtech_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l8_qtech_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l8_qtech_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l8_qtech_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_preview.so:system/vendor/lib/libchromatix_s5k3l8_qtech_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_snapshot.so:system/vendor/lib/libchromatix_s5k3l8_qtech_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_snapshot.so:system/vendor/lib/libchromatix_s5k3l8_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_common.so:system/vendor/lib/libchromatix_s5k3l8_sunny_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_default_video.so:system/vendor/lib/libchromatix_s5k3l8_sunny_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l8_sunny_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l8_sunny_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l8_sunny_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_preview.so:system/vendor/lib/libchromatix_s5k3l8_sunny_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_snapshot.so:system/vendor/lib/libchromatix_s5k3l8_sunny_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_common.so:system/vendor/lib/libchromatix_s5k5e8_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_default_video.so:system/vendor/lib/libchromatix_s5k5e8_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_120fps.so:system/vendor/lib/libchromatix_s5k5e8_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_60fps.so:system/vendor/lib/libchromatix_s5k5e8_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_90fps.so:system/vendor/lib/libchromatix_s5k5e8_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_liveshot.so:system/vendor/lib/libchromatix_s5k5e8_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_preview.so:system/vendor/lib/libchromatix_s5k5e8_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot.so:system/vendor/lib/libchromatix_s5k5e8_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_video_hd.so:system/vendor/lib/libchromatix_s5k5e8_video_hd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_s5k5e8_zsl.so:system/vendor/lib/libchromatix_s5k5e8_zsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_sp2508_common.so:system/vendor/lib/libchromatix_sp2508_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_sp2508_default_video.so:system/vendor/lib/libchromatix_sp2508_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_gc2355_8916_common.so:system/vendor/lib64/libchromatix_gc2355_8916_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_gc2355_8916_default_video.so:system/vendor/lib64/libchromatix_gc2355_8916_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_gc2355_8916_preview.so:system/vendor/lib64/libchromatix_gc2355_8916_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_common.so:system/vendor/lib64/libchromatix_imx219_q8n13a_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_default_video.so:system/vendor/lib64/libchromatix_imx219_q8n13a_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_liveshot.so:system/vendor/lib64/libchromatix_imx219_q8n13a_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_preview.so:system/vendor/lib64/libchromatix_imx219_q8n13a_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_snapshot.so:system/vendor/lib64/libchromatix_imx219_q8n13a_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov13850_default_video.so:system/vendor/lib64/libchromatix_ov13850_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov13853_q13853a_default_video.so:system/vendor/lib64/libchromatix_ov13853_q13853a_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_common.so:system/vendor/lib64/libchromatix_ov8858_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_default_video.so:system/vendor/lib64/libchromatix_ov8858_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_hfr_120fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_120fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_hfr_60fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_60fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_hfr_90fps.so:system/vendor/lib64/libchromatix_ov8858_hfr_90fps.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_liveshot.so:system/vendor/lib64/libchromatix_ov8858_liveshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_preview.so:system/vendor/lib64/libchromatix_ov8858_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_ov8858_snapshot.so:system/vendor/lib64/libchromatix_ov8858_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_sp2508_common.so:system/vendor/lib64/libchromatix_sp2508_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_sp2508_default_video.so:system/vendor/lib64/libchromatix_sp2508_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_sp2508_preview.so:system/vendor/lib64/libchromatix_sp2508_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib64/libchromatix_sp2508_snapshot.so:system/vendor/lib64/libchromatix_sp2508_snapshot.so
